language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - clang-5.0
            - llvm-5.0-dev
      env:
        - CC=clang-5.0
        - CXX=clang++-5.0

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - CC=gcc-7
        - CXX=g++-7

before_install:
  - mkdir build && cd build
  - cmake ..

install:
  - make -j 4

script:
  - python ../tests/run_tests.py ./loxx
